name: CI Pipeline

on:

  push:
    branches:
      - main  # Run on pushes made into the main branch

  pull_request:
    branches:
      - main  # Run on pull requests targeting the main branch

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}  # Checkout the PR branch
          token: ${{ secrets.PRECOMMIT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pytest pre-commit  # Ensuring proper installs

      - name: Run pre-commit and auto-fix
        run: |
          pre-commit run --all-files || true  # Allow to continue even if it fails

      - name: Commit pre-commit fixes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: auto-fix pre-commit issues"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"

      - name: Run pylint
        run: |
          pylint $(git ls-files '*.py') --fail-under=8 #Run Pylint on necessary code (could change to include specified files)
